In [4]:
numbers = [10, 20, 30, 40, 50]#creation of List
print("Original list:", numbers)

numbers.append(60)#here add 60 to list
print("After append:", numbers)

numbers.extend([70, 80])#here add 70 and 80 to list
print("After extend:", numbers)

numbers.insert(2, 25)#here we are inserting an element first is the index position and second is the number we should insert 
print("After insert:", numbers)

numbers.remove(30)#the number 30 is remove form list
print("After remove:", numbers)

numbers.pop()#the pop remove the last number form list
print("After pop:", numbers)

print("Index of 40:", numbers.index(40))#index number of 40

print("Count of 20:", numbers.count(20))#the apperences of that number

numbers.sort()
print("After sort:", numbers)#sort in ascending order


numbers.reverse()
print("After reverse:", numbers)#the sorted number will be show in descending order

numbers.clear()
print("After clear:", numbers)#the list wil complete clear


Original list: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 40, 50, 60, 70, 80]
After pop: [10, 20, 25, 40, 50, 60, 70]
Index of 40: 3
Count of 20: 1
After sort: [10, 20, 25, 40, 50, 60, 70]
After reverse: [70, 60, 50, 40, 25, 20, 10]
After clear: []


In [5]:
students = ("Megha", "Anu", "Rahul")# creating a tuple
print("Original List:", students)#this is the original tuple 
students[1] = "Priya"#here we update a tuple 
print("Updated List:", students)#Tuple is immutable so the elementt cannot change after creation(Faceing error)


Original List: ('Megha', 'Anu', 'Rahul')


TypeError: 'tuple' object does not support item assignment

In [7]:
num ={1,2,2,3,7,8,7,9}#creation of set
print("Set Values:",num)#set will not allow duplicate values

Set Values: {1, 2, 3, 7, 8, 9}


In [9]:
person = {
    "name": "Megha",
    "age": 22,
    "city": "Salem"
}#creation of Dictionary

person["age"] = 23 #change the age to 23
person["email"] = "megh123@gmail.com"#Added email to dictionary

print("Final Dictionary:", person)#the output of dictionary


Final Dictionary: {'name': 'Megha', 'age': 23, 'city': 'Salem', 'email': 'megh123@gmail.com'}


In [10]:
age = int(input("Enter your age: "))#Getting an input
if age >= 18:#the condition statement age should be great or equal 18
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")#if is not then not eligible


Enter your age:  20


You are eligible to vote.


In [16]:
marks = int(input("Enter your marks: "))#getting input
if marks >= 90: #Condition statement: the mark should be greater than or equal to 90 
   print("Grade: A")
elif marks >= 75 and marks <= 89:#the mark should be greater than 75 and less than 89 
   print("Grade: B")
elif marks >= 50 and marks <= 74:#mark should be greater than 50 and less than 74
    print("Grade: C")
else:
    print("Fail")#if is not  come under any condition so is considered as Fail


Enter your marks:  100


Grade: A


In [17]:
num = int(input("Enter a number: "))#getting an input
if num > 0:   #checking if the number is positive
   print("The number is positive")
   if num % 2 == 0:#If it is postive next it should be an even number
      print("It is also even")
   else:
      print("It is positive but odd")#else it is postive and odd number
elif num == 0: #if it is zero 
    print("The number is zero")

else:  #next if the number is not greater than zero is considered as a negative number
    print("The number is negative")


Enter a number:  10


The number is positive
It is also even


In [18]:
import numpy as np #import numpy for using arrays
scalar = np.array(5) #Creating array for 5 
print("Scalar:", scalar)
array1d = np.array([1, 2, 3, 4, 5]) #adding number to an 1D array
print("1D Array:", array1d)

array2d = np.array([[10, 20, 30],#Adding 2D array
                    [40, 50, 60]])
print("2D Array:\n", array2d)



Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


In [19]:
import numpy as np
arr = np.random.randint(0, 100, (4, 4))#random numbers will fill 0 to 100 number in 4D array
print("4x4 Random Array:")
print(arr)



4x4 Random Array:
[[23 51 80 56]
 [95 34 32 25]
 [40 36 76 89]
 [29  1 76 95]]


In [21]:
import numpy as np
import pandas as pd

array = np.array([[1, 2, 3],#creation od 3D array
                  [4, 5, 6],
                  [7, 8, 9]])

df = pd.DataFrame(array, columns=['A', 'B', 'C'])#DataFrame and add column names: 'A', 'B', 'C'.
print(df)


   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [22]:
import pandas as pd

data = {
    'Name': ['Arun', 'Meena', 'Ravi', 'Sita', 'Kumar', 'Anita', 'Ravi', 'John', 'Priya', 'Arun'],
    'Age': [23, 25, 30, 22, 28, 26, 30, 24, 27, 23],
    'City': ['Chennai', 'Coimbatore', 'Madurai', 'Salem', 'Erode', 'Trichy', 'Madurai', 'Chennai', 'Erode', 'Chennai'],
    'Salary': [30000, 35000, None, 28000, 40000, None, 32000, 29000, 36000, 30000]
} #creation and columns: 'Name', 'Age', 'City', and 'Salary'. 

df = pd.DataFrame(data)

print("Info:")
print(df.info())#info of data 

print("\nDescribe:")
print(df.describe())#describe data count, mean, max, std

print("\nSelected Columns:")
print(df[['Name', 'City']])#selectind only name and city columns only

df = df.drop('City', axis=1)
print("\nAfter Dropping City Column:")#Droping the city columns 
print(df)

df['Salary'].fillna(df['Salary'].mean(), inplace=True)
print("\nAfter Filling Missing Salary:")
print(df)

df = df.drop_duplicates()
print("\nAfter Removing Duplicates:")#Remove the duplicate 
print(df)




Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

Describe:
             Age        Salary
count  10.000000      8.000000
mean   25.800000  32500.000000
std     2.898275   4140.393356
min    22.000000  28000.000000
25%    23.250000  29750.000000
50%    25.500000  31000.000000
75%    27.750000  35250.000000
max    30.000000  40000.000000

Selected Columns:
    Name        City
0   Arun     Chennai
1  Meena  Coimbatore
2   Ravi     Madurai
3   Sita       Salem
4  Kumar       Erode
5  Anita      Trichy
6   Ravi     Madurai
7   John     Chennai
8  Priya       Erode
9   Arun     Chennai

After Dropping City Column:
    Name  Age   Salary
0   Aru

C:\Users\megha\AppData\Local\Temp\ipykernel_10420\944793760.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)
